args <- commandArgs(trailingOnly=TRUE)

library("tidyverse", "ggplot2", "dplyr")

var_qual <- read_delim(paste(args, ".lqual", sep = ""), delim="\t", col_names = c("chr", "pos", "qual"), skip = 1)
pdf(paste(args, "-qual.pdf", sep = ""))
a <- ggplot(var_qual, aes(qual)) + geom_density(fill = "red", colour = "black", alpha = 0.25) + xlim(0,100)
a + theme_light()
dev.off()

var_depth <- read_delim(paste(args, ".ldepth.mean", sep = ""), delim = "\t", col_names = c("chr", "pos", "mean_depth", "var_depth"), skip = 1)
pdf(paste(args, "-depth.pdf", sep = ""))
a <- ggplot(var_depth, aes(mean_depth)) + geom_density(fill = "blue", colour = "black", alpha = 0.25) + xlim(0,500)
a + theme_light()
dev.off()
capture.output(summary(var_depth$mean_depth), file = paste(args, "-depth-summary.txt", sep = ""))

var_miss <- read_delim(paste(args, ".lmiss", sep = ""), delim = "\t", col_names = c("chr", "pos", "nchr", "nfiltered", "nmiss", "fmiss"), skip = 1)
pdf(paste(args, "-missing.pdf", sep = ""))
a <- ggplot(var_miss, aes(fmiss)) + geom_density(fill = "green", colour = "black", alpha = 0.25)
a + theme_light()
dev.off()

var_freq <- read_delim(paste(args, ".frq", sep = ""), delim = "\t", col_names = c("chr", "pos", "nalleles", "nchr", "a1", "a2"), skip = 1)
var_freq$maf <- var_freq %>% select(a1, a2) %>% apply(1, function(z) min(z))
pdf(paste(args, "-freq.pdf", sep = ""))
a <- ggplot(var_freq, aes(maf)) + geom_density(fill = "yellow", colour = "black", alpha = 0.25)
a + theme_light()
dev.off()

ind_depth <- read_delim(paste(args, ".idepth", sep = ""), delim = "\t", col_names = c("ind", "nsites", "depth"), skip = 1)
pdf(paste(args, "-ind-depth.pdf", sep = ""))
a <- ggplot(ind_depth, aes(depth)) + geom_histogram(fill = "brown", colour = "black", alpha = 0.25)
a + theme_light()
dev.off()

ind_miss  <- read_delim(paste(args, ".imiss", sep = ""), delim = "\t", col_names = c("ind", "ndata", "nfiltered", "nmiss", "fmiss"), skip = 1)
pdf(paste(args, "-ind-missing.pdf", sep = ""))
a <- ggplot(ind_miss, aes(fmiss)) + geom_histogram(fill = "pink", colour = "black", alpha = 0.25)
a + theme_light()
dev.off()

ind_het  <- read_delim(paste(args, ".het", sep = ""), delim = "\t", col_names = c("ind", "ho", "he", "nsites", "f"), skip = 1)
pdf(paste(args, "-ind-het.pdf", sep = ""))
a <- ggplot(ind_het, aes(f)) + geom_histogram(fill = "purple", colour = "black", alpha = 0.25)
a + theme_light()
dev.off()
